 version: '2'
 services:
   nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: mcat-web-proxy-ngix
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      
